### ISSUE TITLE
Build project structure

### ISSUE THREAD

**Issue by aidanmattrick** [UBC-MDS/Workflows_showcase#1]
Hi all,

Here is the file structure we decided to follow:

<img width="511" alt="Screen Shot 2020-11-18 at 2 22 27 PM" src="https://user-images.githubusercontent.com/40402840/99595394-7f7c5a80-29a9-11eb-8bf1-488c288d8ff0.png">

**Comment by cmmclaug** [comment]
Project organization¶
A good project structure looks similar to this:

project/          
├── data/              *.csv        
│   ├── processed/
│   └── raw/     
├── reports/           *.ipynb *.Rmd
├── src/               *.py *.R
├── doc/               *.md
├── README.md
└── environment.yaml (or renv.lock)
This can differ slightly between projects and for R the src directory is often just called R/, whereas for Python is has the same name as the project (project). You will learn more about project hierarchy when making packages

**Comment by cmmclaug** [comment]
Adding in the extra files required for this task from the milestone document, although there are separate tasks for the team work contract and code of conduct file:

Make sure you create the following 4 files that are important for collaboration:
1. Team work contract
2. Code of Conduct file
3. Contributing file
4. License file

**Comment by cmmclaug** [comment]
Should we add the creation of the README.md to this task as well? @zmerpez had a good reference project README here:
https://github.com/UBC-MDS/DSCI522_GR406

@aidanmattrick suggested using Lucid charts for diagrams:
https://lucid.co/product/lucidchart

**Comment by aidanmattrick** [comment]
How do we feel about dividing the work for this up: 
@cmmclaug maybe you can just create the data directory by adding onto your script? That way we can avoid creating dummy files to initialize the directory.

And whoever is doing the EDA, maybe they can create a reports directory while creating the .ipynb with the EDA?

What are others thoughts? Feel free to ping me on Slack.
