### ISSUE TITLE
Update pre-processing script to clean/transform data for analysis

### ISSUE THREAD

**Issue by cmmclaug** [UBC-MDS/Workflows_showcase#24]
Milestone 2 states:

Write a script that reads the downloaded data and performs and data cleaning/pre-processing, transforming, and/or splitting

This script already exists, but we need to update it based on the following group feedback:
* Update year column to datetime that is just a year number
* Clean up first appearances by converting to datetime, but keep month as text slug. Note that Marvel/DC files have different formats.
* Separate out character rows without alignment values as a 'deployment' set. Not sure if useful, but might as well keep around.
* Separate the rest of the data as train/test split.

**Comment by zmerpez** [comment]
One more thing: group less occurring classes into one, i.e unnatural (hair color), gsm might be divided into 2 as well unspecified and specified. So we can compare yearly effect of characters having gsm or not.
