### ISSUE TITLE
Consolidate EDA into scripts for user consumption

### ISSUE THREAD

**Issue by cmmclaug** [UBC-MDS/Workflows_showcase#25]
Milestone 2 Instructions:

Write a script which creates exploratory data visualization(s) and table(s) that are useful to help the reader/consumer understand that data set

We have our milestone 1 EDA, we just need to focus it for an outside audience so it helps explain the data to match our question. This issue also refers to exporting the nitty gritty of the code to scripts so that the final output is a clean, concise literate document.

**Comment by zmerpez** [comment]
I have created the main eda.py file
TO DO:
1. Get the latest version (after merging PL ) and create new processed csv files by codes in README
2. Try EDA example code and see if tables are created or not.
3. Report any bugs or suggestions
Then, I will:
1. Change eda.py accordingly
2. Fix bugs if any
3. Add Comparison Graphs, may be some sort of correlation
