### ISSUE TITLE
Machine Learning Analysis Script

### ISSUE THREAD

**Issue by cmmclaug** [UBC-MDS/Workflows_showcase#26]
Milestone 2 Statement:

Write a script that performs some statistical or machine learning analysis and summarizes the results as a figure(s) and a table(s)

Take the preprocessed data and create a script to perform machine learning analysis on the data to help answer our question. Have the script output the results in figures or tables to be included in our literate notebook report.

**Comment by zmerpez** [comment]
Here are my suggestions for handling missing values:
Eye: fill=“unknown”?
Hair: fill=“unknown”?
Month(1st appearance): fill =“January” or strategy=“most_frequent”
gsm : fill=“unknown”
Our super hero/villain might be keeping eye color etc. secret =)
