### ISSUE TITLE
Update eda.ipynb

### ISSUE THREAD

**Issue by zmerpez** [UBC-MDS/Workflows_showcase#32]
- Change the processed data used in eda
- Create new profile report by pandas_profiling
- Add a columns to the descriptions of features table that corresponds to type of column (i.e categorical, numerical, binary?)

**Comment by ssyayayy** [comment]
- Tested the processed data used in eda.ipynb. Works as expected. As advised, no need to upload the data sets in the pull request.
- Re-ran the query for creating new profile report. Does not seem to have any changes.
- Added the descriptions of feature types.
- Linked the pull request
