### ISSUE TITLE
Exploratory data analysis

### ISSUE THREAD

**Issue by hsmohammed** [UBC-MDS/Workflows_showcase#36]
- I see that you are creating multiple plots that show the variation of alignment with various variables and with time. I suggest you comment on each plot about why you are creating it and what insights you get from it.

- How do you describe the data points that have "null" alignment and how are you going to deal with it?

**Comment by zmerpez** [comment]
Hi, @hsmohammed for the second point, we did deal with it now and seperated "null" alignment as deployment data. Yet, the explanations needed to be add. Where should we add details about the process (i.e separating deployment train and test sets) , to the report or README?

**Comment by hsmohammed** [comment]
I think you should add that to the EDA file and hint about it in the proposal.
