### ISSUE TITLE
Proposal

### ISSUE THREAD

**Issue by hsmohammed** [UBC-MDS/Workflows_showcase#37]
- You have mentioned 2 research questions, but you haven't mentioned in details how are you going to answer each one. 

- Are you going to look at the temporal autocorrelation? Is logistic regression a suitable tool for that?

- You should write in more details about your proposed methodologies and the variables that you will use in the analysis.

- You should define the main variables like "alignment" to someone who is not familiar with the data set.

**Comment by zmerpez** [comment]
Thanks for your comments @hsmohammed , we will go through those again with group members.

**Comment by ssyayayy** [comment]
- You have mentioned 2 research questions, but you haven't mentioned in details how are you going to answer each one.
> Add details for both questions.

- Are you going to look at the temporal autocorrelation? Is logistic regression a suitable tool for that?
> We haven't studied autocorrelation yet but it is a good topic to look into in the future. You are right, after analyzing the data, logistic regression does not seem to be the best model. We have added more suitable tools for answering that question.

You should write in more details about your proposed methodologies and the variables that you will use in the analysis.
> Added more details

You should define the main variables like "alignment" to someone who is not familiar with the data set.
> Added more explanations

Thanks again for the feedbacks!
