### ISSUE TITLE
Project proposal questions

### ISSUE THREAD

**Issue by cmmclaug** [UBC-MDS/Workflows_showcase#5]
From the Milestone 1 description:

1. Identify a data set, research question, & plan of action for analysis to answer that question
Choose a public data set from the web that you are interested in to carry out a small data analysis. You may also use any data set we have previously worked with in MDS. Correctly cite where your data set is coming from in your proposal. Be sure that it is a data set that is licensed to be shared and used openly on the internet.
2. With your data set, identify one main predictive or inferential research question that you will attempt to answer with analyses and visualizations (more on this below). Clearly state the research question and any natural sub-questions you need to address, and their type.
3. Make a plan of how you will analyze the data (report an estimate and confidence intervals? hypothesis test? classification with a decision tree?). Choose something you already learned how to do in another MDS course.
4. Discuss at least one exploratory data analysis (EDA) table and one exploratory data analysis figure you will create that makes sense for your research question, the data that you have, and the analysis you plan to do.
Suggest how you would share the results of your analysis as one or more tables and/or figures.

**Note - Remember, if you have a predictive research question, it is essential that you separate your dataset before you do any analysis. To be clear, you should NOT do any analysis - including preliminary EDA - on your test data.**

**Comment by cmmclaug** [comment]
I believe we've settled 1, the article and dataset urls below:
https://fivethirtyeight.com/features/women-in-comic-books/
https://github.com/rudeboybert/fivethirtyeight/tree/master/data-raw/comic-characters

**Comment by cmmclaug** [comment]
2 - 4: We need to clarify our research question, here are the notes from the lab meeting:

* Determine variables, particularly physical features and sexual orientation, correlated with good and bad alignment of comic book characters over time.
* Our hypothesis is characters have become more diverse with time
* What are the most important features in determining a comic book characters’ alignment?

I propose we should all work on this ticket to help define the question...

**Comment by zmerpez** [comment]
Thanks Craig, I will prepare a flowchart for 3rd. that will summarize the project plan.

**Comment by zmerpez** [comment]
![flow_chart00](https://user-images.githubusercontent.com/37945511/99641732-88981680-29ff-11eb-84e9-356ea8037670.png)
Hi, I have created a basic template that we can add details, file, script names along the way.

**Comment by aidanmattrick** [comment]
Thanks @cmmclaug and @zmerpez. 
Happy to help with 2 then when we all have input, think this issue should be good to go.
IMO 4 is a separate issue (EDA issue that @cmmclaug created).

**Comment by zmerpez** [comment]
I have made a few changes to the README file, we can change the questions after todays' meeting.
