### ISSUE TITLE
Clean up character names for feature engineering/modelling and create new feature engineering script

### ISSUE THREAD

**Issue by cmmclaug** [UBC-MDS/Workflows_showcase#61]
The character names have a bunch of multiverse and secret identity jargon making them hard to use for for feature modelling and analysis. Split these apart in preprocessing and then add in a feature_engineering.py script into the workflow to support further transformations.

**Comment by zmerpez** [comment]
Thanks, new features seem promising. We just need to add description for new features in summary report.

**Comment by ssyayayy** [comment]
Addressed in the team meeting.
